services:
  app:
    build:
      context: .
      dockerfile: collector_worker/Dockerfile
    container_name: collector_worker
    restart: unless-stopped
    networks:
      - debt_collector_net
    environment:
      - MONGO_URI=mongodb://root:rootpassword@mongo:27018/debt_collector?authSource=admin
      - TZ=America/Maceio
      - DEBUG=false
    volumes:
      - ./collector_worker:/app
    command: python main.py --job service --debug
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: debt_collector_mongo
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - debt_collector_net

volumes:
  mongo_data:

networks:
  debt_collector_net:
    driver: bridge