services:
  app:
    build: .
    container_name: debt_collector_app
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      # - MONGO_URI=mongodb://mongo:27017/debt_collector
      - MONGO_URI=mongodb://root:rootpassword@192.168.107.4:27017/?authSource=admin
      - TZ=America/Maceio
      - DEBUG=false
    volumes:
      - ./app:/app
    command: python main.py --job service

  mongo:
    image: mongo:latest
    container_name: debt_collector_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: